Imports System.Data.OleDb
Imports System.Data
Imports System.IO

Module Globals

    Friend Enum PRG_DIALOGMODE
        DM_ADD = 0
        DM_EDIT = 1
    End Enum

    Friend Enum E_DATASOURCETYPE
        DST_NONE = 0
        DST_ACCESS = 1
        DST_XML = 2
    End Enum

    Public Function GetTextNum(ByRef oControl As TextBox, ByVal lDefault As Integer) As Integer
        Dim sReturn As String
        sReturn = oControl.Text
        If sReturn.Length = 0 Then
            Return lDefault
        End If
        If (IsNumeric(sReturn) = False) Then
            Return lDefault
        End If
        Return System.Convert.ToInt32(sReturn)
    End Function

    Public Function g_GetAppLocation() As String
        Return AppDomain.CurrentDomain.BaseDirectory.Replace("\bin\", "")
    End Function

    Public Function g_ReadFile(ByVal sFullPath As String, Optional ByVal bDetectEncoding As Boolean = False, Optional ByVal oEncoding As System.Text.Encoding = Nothing) As String
        Dim oReader As StreamReader
        If bDetectEncoding = False Then
            If oEncoding Is Nothing Then
                oReader = New StreamReader(sFullPath)
            Else
                oReader = New StreamReader(sFullPath, oEncoding)
            End If
        Else
            oReader = New StreamReader(sFullPath, True)
        End If
        Dim sReturn As String = oReader.ReadToEnd()
        oReader.Close()
        Return sReturn
    End Function

    Public Sub g_WriteFile(ByVal sFullPath As String, ByVal sFileContents As String, Optional ByVal oEncoding As System.Text.Encoding = Nothing)
        Dim oWriter As StreamWriter
        If oEncoding Is Nothing Then
            oWriter = New StreamWriter(sFullPath)
        Else
            oWriter = New StreamWriter(sFullPath, False, oEncoding)
        End If
        oWriter.Write(sFileContents)
        oWriter.Close()
    End Sub

    Public Sub g_VerifyWriteAccess(ByVal sDirectory As String)
        Dim sFullPath As String = g_GetAppLocation() & "\" & sDirectory & "\"
        Try
            g_WriteFile(sFullPath & "test.txt", "TestFile")
            Dim oFile As New FileInfo(sFullPath & "test.txt")
            If oFile.Exists = True Then
                oFile.Delete()
            End If
        Catch ex As Exception
            MsgBox("In order for this example to work correctly full access to the """ & sFullPath & """ must be granted, you can do so by running this application as an Administrator or manually configuring permissions.", MsgBoxStyle.OkOnly)
        End Try
    End Sub

    Public Function GetRnd(ByVal lLowerBound As Integer, ByVal lUpperBound As Integer) As Integer
        Dim oRnd As System.Random = Nothing
        Dim sGUID As String = System.Guid.NewGuid().ToString("N").Replace("a", "").Replace("b", "").Replace("c", "").Replace("d", "").Replace("e", "").Replace("f", "")
        Dim iSeed As Integer = CType(sGUID.Substring(0, 5), System.Int32)
        oRnd = New Random(iSeed)
        Return oRnd.Next(lLowerBound, lUpperBound)
    End Function

    Public Function g_Format(ByVal dParam As Double, ByVal sFormat As String) As String
        Return dParam.ToString(sFormat)
    End Function

    Public Function g_GetComboBoxSelectedItem(ByRef oComboBox As ComboBox, ByVal sColumnName As String) As String
        Dim sReturn As String
        Dim oDataRowView As DataRowView
        oDataRowView = DirectCast(oComboBox.SelectedItem, System.Data.DataRowView)
        sReturn = CType(oDataRowView.Item(sColumnName), System.String)
        Return sReturn
    End Function

    Public Function g_GenerateRandomName(ByVal IncludePrefix As Boolean, ByVal yDataSourceType As E_DATASOURCETYPE) As String
        Dim sReturn As String = ""
        Dim oDataRow As DataRow = Nothing
        If yDataSourceType = E_DATASOURCETYPE.DST_ACCESS Then
            Using oConn As New OleDbConnection(g_DST_ACCESS_GetConnectionString())
                Dim oCmd As OleDbCommand = Nothing
                Dim oReader As OleDbDataReader = Nothing
                oConn.Open()
                oCmd = New OleDbCommand("SELECT * FROM tb_First_Names WHERE ID=" & GetRnd(1, 5494).ToString(), oConn)
                oReader = oCmd.ExecuteReader
                If oReader.Read = True Then
                    If IncludePrefix = True Then
                        If DirectCast(oReader.Item("sSex"), System.String) = "F" Then
                            sReturn = "Ms. "
                        Else
                            sReturn = "Mr. "
                        End If
                    End If
                    sReturn = sReturn & DirectCast(oReader.Item("Name"), System.String)
                End If
                oReader.Close()
                oCmd = New OleDbCommand("SELECT * FROM tb_Last_Names WHERE ID=" & GetRnd(1, 88799).ToString(), oConn)
                oReader = oCmd.ExecuteReader
                If oReader.Read = True Then
                    sReturn = sReturn & " " & DirectCast(oReader.Item("LastName"), System.String)
                End If
                oReader.Close()
                oConn.Close()
            End Using
        ElseIf yDataSourceType = E_DATASOURCETYPE.DST_XML Then
            Dim otb_First_Names As DataSet = Nothing
            Dim oKeys_tb_First_Names(0) As DataColumn
            Dim otb_Last_Names As DataSet = Nothing
            Dim oKeys_tb_Last_Names(0) As DataColumn

            otb_First_Names = New DataSet()
            otb_First_Names.ReadXmlSchema(g_GetAppLocation() & "\CR_XML\tb_First_Names.xsd")
            otb_First_Names.ReadXml(g_GetAppLocation() & "\CR_XML\tb_First_Names.xml")
            oKeys_tb_First_Names(0) = otb_First_Names.Tables(1).Columns("ID")
            otb_First_Names.Tables(1).PrimaryKey = oKeys_tb_First_Names

            oDataRow = otb_First_Names.Tables(1).Rows(GetRnd(1, 200) - 1)

            If IncludePrefix = True Then
                If DirectCast(oDataRow("sSex"), System.String) = "F" Then
                    sReturn = "Ms. "
                Else
                    sReturn = "Mr. "
                End If
            End If
            sReturn = sReturn & DirectCast(oDataRow("Name"), System.String)

            otb_Last_Names = New DataSet()
            otb_Last_Names.ReadXmlSchema(g_GetAppLocation() & "\CR_XML\tb_Last_Names.xsd")
            otb_Last_Names.ReadXml(g_GetAppLocation() & "\CR_XML\tb_Last_Names.xml")
            oKeys_tb_Last_Names(0) = otb_Last_Names.Tables(1).Columns("ID")
            otb_Last_Names.Tables(1).PrimaryKey = oKeys_tb_Last_Names

            oDataRow = otb_Last_Names.Tables(1).Rows(GetRnd(1, 200) - 1)

            sReturn = sReturn & " " & DirectCast(oDataRow("LastName"), System.String)

        ElseIf yDataSourceType = E_DATASOURCETYPE.DST_NONE Then
            Dim oKeys_tb_First_Names(0) As DataColumn
            Dim oTable_tb_First_Names As New DataTable("tb_First_Names")

            oTable_tb_First_Names.Columns.Add("ID", Type.GetType("System.Int32"))
            oTable_tb_First_Names.Columns.Add("Name", Type.GetType("System.String"))
            oTable_tb_First_Names.Columns.Add("sSex", Type.GetType("System.String"))

            oKeys_tb_First_Names(0) = oTable_tb_First_Names.Columns("ID")
            oTable_tb_First_Names.PrimaryKey = oKeys_tb_First_Names

            NoDataSource_Add_First_Names(oTable_tb_First_Names)

            oDataRow = oTable_tb_First_Names.Rows(GetRnd(1, 200) - 1)

            If IncludePrefix = True Then
                If DirectCast(oDataRow("sSex"), System.String) = "F" Then
                    sReturn = "Ms. "
                Else
                    sReturn = "Mr. "
                End If
            End If
            sReturn = sReturn & DirectCast(oDataRow("Name"), System.String)

            Dim oKeys_tb_Last_Names(0) As DataColumn
            Dim oTable_tb_Last_Names As New DataTable("tb_Last_Names")

            oTable_tb_Last_Names.Columns.Add("ID", Type.GetType("System.Int32"))
            oTable_tb_Last_Names.Columns.Add("LastName", Type.GetType("System.String"))

            oKeys_tb_Last_Names(0) = oTable_tb_Last_Names.Columns("ID")
            oTable_tb_Last_Names.PrimaryKey = oKeys_tb_Last_Names

            NoDataSource_Add_Last_Names(oTable_tb_Last_Names)

            oDataRow = oTable_tb_Last_Names.Rows(GetRnd(1, 200) - 1)

            sReturn = sReturn & " " & DirectCast(oDataRow("LastName"), System.String)

        End If
        Return sReturn
    End Function

    Public Function g_GenerateRandomAddress(ByVal yDataSourceType As E_DATASOURCETYPE) As String
        Dim sReturn As String = ""
        Dim i As Integer = 0
        Dim Max As Integer = 0
        Dim oDataRow As DataRow = Nothing

        Max = GetRnd(1, 3)
        For i = 1 To Max
            sReturn = sReturn & Chr(GetRnd(49, 57))
        Next

        If yDataSourceType = E_DATASOURCETYPE.DST_ACCESS Then
            Using oConn As New OleDbConnection(g_DST_ACCESS_GetConnectionString())
                Dim oCmd As OleDbCommand = Nothing
                Dim oReader As OleDbDataReader = Nothing
                oConn.Open()
                oCmd = New OleDbCommand("SELECT * FROM tb_Last_Names WHERE ID=" & GetRnd(1, 88799).ToString(), oConn)
                oReader = oCmd.ExecuteReader
                If oReader.Read = True Then
                    sReturn = sReturn & " " & DirectCast(oReader.Item("LastName"), System.String)
                End If
                oReader.Close()
                oCmd = New OleDbCommand("SELECT * FROM tb_US_Streets WHERE ID=" & GetRnd(1, 538).ToString(), oConn)
                oReader = oCmd.ExecuteReader
                If oReader.Read = True Then
                    sReturn = sReturn & " " & DirectCast(oReader.Item("Name"), System.String)
                End If
                oReader.Close()
                oConn.Close()
            End Using

        ElseIf yDataSourceType = E_DATASOURCETYPE.DST_XML Then
            Dim otb_Last_Names As DataSet = Nothing
            Dim oKeys_tb_Last_Names(0) As DataColumn
            Dim otb_US_Streets As DataSet = Nothing
            Dim oKeys_tb_US_Streets(0) As DataColumn


            otb_Last_Names = New DataSet()
            otb_Last_Names.ReadXmlSchema(g_GetAppLocation() & "\CR_XML\tb_Last_Names.xsd")
            otb_Last_Names.ReadXml(g_GetAppLocation() & "\CR_XML\tb_Last_Names.xml")
            oKeys_tb_Last_Names(0) = otb_Last_Names.Tables(1).Columns("ID")
            otb_Last_Names.Tables(1).PrimaryKey = oKeys_tb_Last_Names

            oDataRow = otb_Last_Names.Tables(1).Rows(GetRnd(1, 200) - 1)

            sReturn = sReturn & " " & DirectCast(oDataRow("LastName"), System.String)

            otb_US_Streets = New DataSet()
            otb_US_Streets.ReadXmlSchema(g_GetAppLocation() & "\CR_XML\tb_US_Streets.xsd")
            otb_US_Streets.ReadXml(g_GetAppLocation() & "\CR_XML\tb_US_Streets.xml")
            oKeys_tb_US_Streets(0) = otb_US_Streets.Tables(1).Columns("ID")
            otb_US_Streets.Tables(1).PrimaryKey = oKeys_tb_US_Streets

            oDataRow = otb_US_Streets.Tables(1).Rows(GetRnd(1, 538) - 1)

            sReturn = sReturn & " " & DirectCast(oDataRow("Name"), System.String)

        ElseIf yDataSourceType = E_DATASOURCETYPE.DST_NONE Then
            Dim oKeys_tb_Last_Names(0) As DataColumn
            Dim oTable_tb_Last_Names As New DataTable("tb_Last_Names")
            Dim oKeys_tb_US_Streets(0) As DataColumn
            Dim oTable_tb_US_Streets As New DataTable("tb_US_Streets")

            oTable_tb_Last_Names.Columns.Add("ID", Type.GetType("System.Int32"))
            oTable_tb_Last_Names.Columns.Add("LastName", Type.GetType("System.String"))

            oKeys_tb_Last_Names(0) = oTable_tb_Last_Names.Columns("ID")
            oTable_tb_Last_Names.PrimaryKey = oKeys_tb_Last_Names

            NoDataSource_Add_Last_Names(oTable_tb_Last_Names)

            oDataRow = oTable_tb_Last_Names.Rows(GetRnd(1, 200) - 1)

            sReturn = sReturn & " " & DirectCast(oDataRow("LastName"), System.String)

            oTable_tb_US_Streets.Columns.Add("ID", Type.GetType("System.Int32"))
            oTable_tb_US_Streets.Columns.Add("Name", Type.GetType("System.String"))
            oTable_tb_US_Streets.Columns.Add("USPS", Type.GetType("System.String"))

            oKeys_tb_US_Streets(0) = oTable_tb_US_Streets.Columns("ID")
            oTable_tb_US_Streets.PrimaryKey = oKeys_tb_US_Streets

            NoDataSource_Add_US_Streets(oTable_tb_US_Streets)

            oDataRow = oTable_tb_US_Streets.Rows(GetRnd(1, 538) - 1)

            sReturn = sReturn & " " & DirectCast(oDataRow("Name"), System.String)
        End If
        Return sReturn
    End Function

    Public Sub g_GenerateRandomCity(ByRef sCityName As String, ByRef sState As String, ByRef ID As Integer, ByVal yDataSourceType As E_DATASOURCETYPE)
        Dim oDataRow As DataRow = Nothing
        If yDataSourceType = E_DATASOURCETYPE.DST_ACCESS Then
            Using oConn As New OleDbConnection(g_DST_ACCESS_GetConnectionString())
                Dim oCmd As OleDbCommand = Nothing
                Dim oReader As OleDbDataReader = Nothing
                oConn.Open()
                oCmd = New OleDbCommand("SELECT * FROM tb_US_Cities WHERE ID=" & GetRnd(1, 25150).ToString(), oConn)
                oReader = oCmd.ExecuteReader
                If oReader.Read = True Then
                    sCityName = DirectCast(oReader.Item("Name"), System.String)
                    sState = DirectCast(oReader.Item("State"), System.String)
                    ID = DirectCast(oReader.Item("ID"), System.Int32)
                    sCityName = Trim(sCityName)
                    sState = Trim(sState)
                End If
                oConn.Close()
            End Using
        ElseIf yDataSourceType = E_DATASOURCETYPE.DST_XML Then
            Dim otb_US_Cities As DataSet = Nothing
            Dim oKeys_tb_US_Cities(0) As DataColumn

            otb_US_Cities = New DataSet()
            otb_US_Cities.ReadXmlSchema(g_GetAppLocation() & "\CR_XML\tb_US_Cities.xsd")
            otb_US_Cities.ReadXml(g_GetAppLocation() & "\CR_XML\tb_US_Cities.xml")
            oKeys_tb_US_Cities(0) = otb_US_Cities.Tables(1).Columns("ID")
            otb_US_Cities.Tables(1).PrimaryKey = oKeys_tb_US_Cities

            oDataRow = otb_US_Cities.Tables(1).Rows(GetRnd(1, 200) - 1)
            sCityName = DirectCast(oDataRow("Name"), System.String)
            sState = DirectCast(oDataRow("State"), System.String)
            ID = DirectCast(oDataRow("ID"), System.Int32)
            sCityName = Trim(sCityName)
            sState = Trim(sState)
        ElseIf yDataSourceType = E_DATASOURCETYPE.DST_NONE Then
            Dim oKeys_tb_US_Cities(0) As DataColumn
            Dim oTable_tb_US_Cities As New DataTable("tb_US_Cities")

            oTable_tb_US_Cities.Columns.Add("ID", Type.GetType("System.Int32"))
            oTable_tb_US_Cities.Columns.Add("Name", Type.GetType("System.String"))
            oTable_tb_US_Cities.Columns.Add("State", Type.GetType("System.String"))

            oKeys_tb_US_Cities(0) = oTable_tb_US_Cities.Columns("ID")
            oTable_tb_US_Cities.PrimaryKey = oKeys_tb_US_Cities

            NoDataSource_Add_US_Cities(oTable_tb_US_Cities)

            oDataRow = oTable_tb_US_Cities.Rows(GetRnd(1, 200) - 1)
            sCityName = DirectCast(oDataRow("Name"), System.String)
            sState = DirectCast(oDataRow("State"), System.String)
            ID = DirectCast(oDataRow("ID"), System.Int32)
            sCityName = Trim(sCityName)
            sState = Trim(sState)
        End If
    End Sub

    Public Function g_GenerateRandomPhone(ByVal AreaCode As String) As String
        Dim i As Integer = 0
        Dim sBuff As String = ""
        If AreaCode = "" Then
            For i = 1 To 3
                If i = 1 Then
                    sBuff = sBuff & Chr(GetRnd(49, 57))
                Else
                    sBuff = sBuff & Chr(GetRnd(48, 57))
                End If
            Next i
            sBuff = "(" & sBuff & ") "
        Else
            sBuff = AreaCode & " "
        End If
        For i = 1 To 3
            If i = 1 Then
                sBuff = sBuff & Chr(GetRnd(49, 57))
            Else
                sBuff = sBuff & Chr(GetRnd(48, 57))
            End If
        Next i
        sBuff = sBuff & "-"
        For i = 1 To 4
            sBuff = sBuff & Chr(GetRnd(48, 57))
        Next i
        Return sBuff
    End Function

    Public Function g_GenerateRandomZIP() As String
        Dim i As Integer = 0
        Dim sBuff As String = ""
        For i = 1 To 5
            If i = 1 Then
                sBuff = sBuff & Chr(GetRnd(49, 57))
            Else
                sBuff = sBuff & Chr(GetRnd(48, 57))
            End If
        Next i
        Return sBuff
    End Function

    Public Function g_GenerateRandomLicense() As String
        Dim i As Integer = 0
        Dim sBuff As String = ""
        For i = 1 To 3
            sBuff = sBuff & Chr(GetRnd(65, 90))
        Next i
        sBuff = sBuff & "-"
        For i = 1 To 4
            sBuff = sBuff & Chr(GetRnd(48, 57))
        Next i
        Return sBuff
    End Function

    Private Sub NoDataSource_Add_First_Names(ByRef oDataTable As DataTable)
        NoDataSource_Add_First_Name(oDataTable, 1, "Fidelia", "F")
        NoDataSource_Add_First_Name(oDataTable, 2, "Eladia", "F")
        NoDataSource_Add_First_Name(oDataTable, 3, "Elizabet", "F")
        NoDataSource_Add_First_Name(oDataTable, 4, "Elsy", "F")
        NoDataSource_Add_First_Name(oDataTable, 5, "Estefana", "F")
        NoDataSource_Add_First_Name(oDataTable, 6, "Eulah", "F")
        NoDataSource_Add_First_Name(oDataTable, 7, "Carylon", "F")
        NoDataSource_Add_First_Name(oDataTable, 8, "Mae", "F")
        NoDataSource_Add_First_Name(oDataTable, 9, "Misty", "F")
        NoDataSource_Add_First_Name(oDataTable, 10, "Julio", "M")
        NoDataSource_Add_First_Name(oDataTable, 11, "Cody", "M")
        NoDataSource_Add_First_Name(oDataTable, 12, "Lance", "M")
        NoDataSource_Add_First_Name(oDataTable, 13, "Kelly", "M")
        NoDataSource_Add_First_Name(oDataTable, 14, "Tyrone", "M")
        NoDataSource_Add_First_Name(oDataTable, 15, "Darren", "M")
        NoDataSource_Add_First_Name(oDataTable, 16, "Lonnie", "M")
        NoDataSource_Add_First_Name(oDataTable, 17, "Mathew", "M")
        NoDataSource_Add_First_Name(oDataTable, 18, "Ted", "M")
        NoDataSource_Add_First_Name(oDataTable, 19, "Toni", "F")
        NoDataSource_Add_First_Name(oDataTable, 20, "Javier", "M")
        NoDataSource_Add_First_Name(oDataTable, 21, "Kristina", "F")
        NoDataSource_Add_First_Name(oDataTable, 22, "Violet", "F")
        NoDataSource_Add_First_Name(oDataTable, 23, "Jessie", "M")
        NoDataSource_Add_First_Name(oDataTable, 24, "Christian", "M")
        NoDataSource_Add_First_Name(oDataTable, 25, "Fernando", "M")
        NoDataSource_Add_First_Name(oDataTable, 26, "Bobbie", "F")
        NoDataSource_Add_First_Name(oDataTable, 27, "Clinton", "M")
        NoDataSource_Add_First_Name(oDataTable, 28, "Neil", "M")
        NoDataSource_Add_First_Name(oDataTable, 29, "Miriam", "F")
        NoDataSource_Add_First_Name(oDataTable, 30, "Velma", "F")
        NoDataSource_Add_First_Name(oDataTable, 31, "Jamie", "M")
        NoDataSource_Add_First_Name(oDataTable, 32, "Becky", "F")
        NoDataSource_Add_First_Name(oDataTable, 33, "Darryl", "M")
        NoDataSource_Add_First_Name(oDataTable, 34, "Sonia", "F")
        NoDataSource_Add_First_Name(oDataTable, 35, "Claude", "M")
        NoDataSource_Add_First_Name(oDataTable, 36, "Cory", "M")
        NoDataSource_Add_First_Name(oDataTable, 37, "Jenny", "F")
        NoDataSource_Add_First_Name(oDataTable, 38, "Erik", "M")
        NoDataSource_Add_First_Name(oDataTable, 39, "Felicia", "F")
        NoDataSource_Add_First_Name(oDataTable, 40, "Adrian", "M")
        NoDataSource_Add_First_Name(oDataTable, 41, "Karl", "M")
        NoDataSource_Add_First_Name(oDataTable, 42, "Mae", "F")
        NoDataSource_Add_First_Name(oDataTable, 43, "Misty", "F")
        NoDataSource_Add_First_Name(oDataTable, 44, "Julio", "M")
        NoDataSource_Add_First_Name(oDataTable, 45, "Cody", "M")
        NoDataSource_Add_First_Name(oDataTable, 46, "Lance", "M")
        NoDataSource_Add_First_Name(oDataTable, 47, "Kelly", "M")
        NoDataSource_Add_First_Name(oDataTable, 48, "Tyrone", "M")
        NoDataSource_Add_First_Name(oDataTable, 49, "Darren", "M")
        NoDataSource_Add_First_Name(oDataTable, 50, "Lonnie", "M")
        NoDataSource_Add_First_Name(oDataTable, 51, "Mathew", "M")
        NoDataSource_Add_First_Name(oDataTable, 52, "Ted", "M")
        NoDataSource_Add_First_Name(oDataTable, 53, "Toni", "F")
        NoDataSource_Add_First_Name(oDataTable, 54, "Javier", "M")
        NoDataSource_Add_First_Name(oDataTable, 55, "Kristina", "F")
        NoDataSource_Add_First_Name(oDataTable, 56, "Violet", "F")
        NoDataSource_Add_First_Name(oDataTable, 57, "Jessie", "M")
        NoDataSource_Add_First_Name(oDataTable, 58, "Christian", "M")
        NoDataSource_Add_First_Name(oDataTable, 59, "Fernando", "M")
        NoDataSource_Add_First_Name(oDataTable, 60, "Bobbie", "F")
        NoDataSource_Add_First_Name(oDataTable, 61, "Clinton", "M")
        NoDataSource_Add_First_Name(oDataTable, 62, "Neil", "M")
        NoDataSource_Add_First_Name(oDataTable, 63, "Miriam", "F")
        NoDataSource_Add_First_Name(oDataTable, 64, "Velma", "F")
        NoDataSource_Add_First_Name(oDataTable, 65, "Jamie", "M")
        NoDataSource_Add_First_Name(oDataTable, 66, "Becky", "F")
        NoDataSource_Add_First_Name(oDataTable, 67, "Darryl", "M")
        NoDataSource_Add_First_Name(oDataTable, 68, "Sonia", "F")
        NoDataSource_Add_First_Name(oDataTable, 69, "Claude", "M")
        NoDataSource_Add_First_Name(oDataTable, 70, "Cory", "M")
        NoDataSource_Add_First_Name(oDataTable, 71, "Jenny", "F")
        NoDataSource_Add_First_Name(oDataTable, 72, "Erik", "M")
        NoDataSource_Add_First_Name(oDataTable, 73, "Felicia", "F")
        NoDataSource_Add_First_Name(oDataTable, 74, "Adrian", "M")
        NoDataSource_Add_First_Name(oDataTable, 75, "Margy", "F")
        NoDataSource_Add_First_Name(oDataTable, 76, "Lenita", "F")
        NoDataSource_Add_First_Name(oDataTable, 77, "Mae", "F")
        NoDataSource_Add_First_Name(oDataTable, 78, "Misty", "F")
        NoDataSource_Add_First_Name(oDataTable, 79, "Julio", "M")
        NoDataSource_Add_First_Name(oDataTable, 80, "Cody", "M")
        NoDataSource_Add_First_Name(oDataTable, 81, "Lance", "M")
        NoDataSource_Add_First_Name(oDataTable, 82, "Kelly", "M")
        NoDataSource_Add_First_Name(oDataTable, 83, "Tyrone", "M")
        NoDataSource_Add_First_Name(oDataTable, 84, "Darren", "M")
        NoDataSource_Add_First_Name(oDataTable, 85, "Lonnie", "M")
        NoDataSource_Add_First_Name(oDataTable, 86, "Mathew", "M")
        NoDataSource_Add_First_Name(oDataTable, 87, "Ted", "M")
        NoDataSource_Add_First_Name(oDataTable, 88, "Toni", "F")
        NoDataSource_Add_First_Name(oDataTable, 89, "Mae", "F")
        NoDataSource_Add_First_Name(oDataTable, 90, "Misty", "F")
        NoDataSource_Add_First_Name(oDataTable, 91, "Julio", "M")
        NoDataSource_Add_First_Name(oDataTable, 92, "Cody", "M")
        NoDataSource_Add_First_Name(oDataTable, 93, "Lance", "M")
        NoDataSource_Add_First_Name(oDataTable, 94, "Kelly", "M")
        NoDataSource_Add_First_Name(oDataTable, 95, "Tyrone", "M")
        NoDataSource_Add_First_Name(oDataTable, 96, "Darren", "M")
        NoDataSource_Add_First_Name(oDataTable, 97, "Lonnie", "M")
        NoDataSource_Add_First_Name(oDataTable, 98, "Mathew", "M")
        NoDataSource_Add_First_Name(oDataTable, 99, "Ted", "M")
        NoDataSource_Add_First_Name(oDataTable, 100, "Toni", "F")
        NoDataSource_Add_First_Name(oDataTable, 101, "Javier", "M")
        NoDataSource_Add_First_Name(oDataTable, 102, "Kristina", "F")
        NoDataSource_Add_First_Name(oDataTable, 103, "Violet", "F")
        NoDataSource_Add_First_Name(oDataTable, 104, "Jessie", "M")
        NoDataSource_Add_First_Name(oDataTable, 105, "Christian", "M")
        NoDataSource_Add_First_Name(oDataTable, 106, "Fernando", "M")
        NoDataSource_Add_First_Name(oDataTable, 107, "Bobbie", "F")
        NoDataSource_Add_First_Name(oDataTable, 108, "Clinton", "M")
        NoDataSource_Add_First_Name(oDataTable, 109, "Neil", "M")
        NoDataSource_Add_First_Name(oDataTable, 110, "Miriam", "F")
        NoDataSource_Add_First_Name(oDataTable, 111, "Velma", "F")
        NoDataSource_Add_First_Name(oDataTable, 112, "Jamie", "M")
        NoDataSource_Add_First_Name(oDataTable, 113, "Becky", "F")
        NoDataSource_Add_First_Name(oDataTable, 114, "Darryl", "M")
        NoDataSource_Add_First_Name(oDataTable, 115, "Sonia", "F")
        NoDataSource_Add_First_Name(oDataTable, 116, "Claude", "M")
        NoDataSource_Add_First_Name(oDataTable, 117, "Naomi", "F")
        NoDataSource_Add_First_Name(oDataTable, 118, "Priscilla", "F")
        NoDataSource_Add_First_Name(oDataTable, 119, "Kay", "F")
        NoDataSource_Add_First_Name(oDataTable, 120, "Penny", "F")
        NoDataSource_Add_First_Name(oDataTable, 121, "Jared", "M")
        NoDataSource_Add_First_Name(oDataTable, 122, "Carole", "F")
        NoDataSource_Add_First_Name(oDataTable, 123, "Leah", "F")
        NoDataSource_Add_First_Name(oDataTable, 124, "Roland", "M")
        NoDataSource_Add_First_Name(oDataTable, 125, "Ron", "M")
        NoDataSource_Add_First_Name(oDataTable, 126, "Nina", "F")
        NoDataSource_Add_First_Name(oDataTable, 127, "Mitchell", "M")
        NoDataSource_Add_First_Name(oDataTable, 128, "Arnold", "M")
        NoDataSource_Add_First_Name(oDataTable, 129, "Harvey", "M")
        NoDataSource_Add_First_Name(oDataTable, 130, "Margie", "F")
        NoDataSource_Add_First_Name(oDataTable, 131, "Cassandra", "F")
        NoDataSource_Add_First_Name(oDataTable, 132, "Nora", "F")
        NoDataSource_Add_First_Name(oDataTable, 133, "Brad", "M")
        NoDataSource_Add_First_Name(oDataTable, 134, "Gabriel", "M")
        NoDataSource_Add_First_Name(oDataTable, 135, "Jennie", "F")
        NoDataSource_Add_First_Name(oDataTable, 136, "Elmer", "M")
        NoDataSource_Add_First_Name(oDataTable, 137, "Gwendolyn", "F")
        NoDataSource_Add_First_Name(oDataTable, 138, "Hilda", "F")
        NoDataSource_Add_First_Name(oDataTable, 139, "Andre", "M")
        NoDataSource_Add_First_Name(oDataTable, 140, "Deanna", "F")
        NoDataSource_Add_First_Name(oDataTable, 141, "Patsy", "F")
        NoDataSource_Add_First_Name(oDataTable, 142, "Duane", "M")
        NoDataSource_Add_First_Name(oDataTable, 143, "Franklin", "M")
        NoDataSource_Add_First_Name(oDataTable, 144, "Lena", "F")
        NoDataSource_Add_First_Name(oDataTable, 145, "Christy", "F")
        NoDataSource_Add_First_Name(oDataTable, 146, "Myrtle", "F")
        NoDataSource_Add_First_Name(oDataTable, 147, "Marsha", "F")
        NoDataSource_Add_First_Name(oDataTable, 148, "Mabel", "F")
        NoDataSource_Add_First_Name(oDataTable, 149, "Ben", "M")
        NoDataSource_Add_First_Name(oDataTable, 150, "Chester", "M")
        NoDataSource_Add_First_Name(oDataTable, 151, "Cecil", "M")
        NoDataSource_Add_First_Name(oDataTable, 152, "Raul", "M")
        NoDataSource_Add_First_Name(oDataTable, 153, "Maxine", "F")
        NoDataSource_Add_First_Name(oDataTable, 154, "Irma", "F")
        NoDataSource_Add_First_Name(oDataTable, 155, "Terry", "F")
        NoDataSource_Add_First_Name(oDataTable, 156, "Edgar", "M")
        NoDataSource_Add_First_Name(oDataTable, 157, "Milton", "M")
        NoDataSource_Add_First_Name(oDataTable, 158, "Leslie", "M")
        NoDataSource_Add_First_Name(oDataTable, 159, "Rafael", "M")
        NoDataSource_Add_First_Name(oDataTable, 160, "Nathaniel", "M")
        NoDataSource_Add_First_Name(oDataTable, 161, "Mattie", "F")
        NoDataSource_Add_First_Name(oDataTable, 162, "Vickie", "F")
        NoDataSource_Add_First_Name(oDataTable, 163, "Angel", "M")
        NoDataSource_Add_First_Name(oDataTable, 164, "Ruben", "M")
        NoDataSource_Add_First_Name(oDataTable, 165, "Brett", "M")
        NoDataSource_Add_First_Name(oDataTable, 166, "Jo", "F")
        NoDataSource_Add_First_Name(oDataTable, 167, "Dora", "F")
        NoDataSource_Add_First_Name(oDataTable, 168, "Reginald", "M")
        NoDataSource_Add_First_Name(oDataTable, 169, "Caroline", "F")
        NoDataSource_Add_First_Name(oDataTable, 170, "Stella", "F")
        NoDataSource_Add_First_Name(oDataTable, 171, "Lydia", "F")
        NoDataSource_Add_First_Name(oDataTable, 172, "Viola", "F")
        NoDataSource_Add_First_Name(oDataTable, 173, "Courtney", "F")
        NoDataSource_Add_First_Name(oDataTable, 174, "Marian", "F")
        NoDataSource_Add_First_Name(oDataTable, 175, "Gene", "M")
        NoDataSource_Add_First_Name(oDataTable, 176, "Marc", "M")
        NoDataSource_Add_First_Name(oDataTable, 177, "Marlene", "F")
        NoDataSource_Add_First_Name(oDataTable, 178, "Glenda", "F")
        NoDataSource_Add_First_Name(oDataTable, 179, "Heidi", "F")
        NoDataSource_Add_First_Name(oDataTable, 180, "Nellie", "F")
        NoDataSource_Add_First_Name(oDataTable, 181, "Tanya", "F")
        NoDataSource_Add_First_Name(oDataTable, 182, "Tyler", "M")
        NoDataSource_Add_First_Name(oDataTable, 183, "Gilbert", "M")
        NoDataSource_Add_First_Name(oDataTable, 184, "Minnie", "F")
        NoDataSource_Add_First_Name(oDataTable, 185, "Jackie", "F")
        NoDataSource_Add_First_Name(oDataTable, 186, "Claudia", "F")
        NoDataSource_Add_First_Name(oDataTable, 187, "Lillie", "F")
        NoDataSource_Add_First_Name(oDataTable, 188, "Brent", "M")
        NoDataSource_Add_First_Name(oDataTable, 189, "Ramon", "M")
        NoDataSource_Add_First_Name(oDataTable, 190, "Charlie", "M")
        NoDataSource_Add_First_Name(oDataTable, 191, "Marcia", "F")
        NoDataSource_Add_First_Name(oDataTable, 192, "Georgia", "F")
        NoDataSource_Add_First_Name(oDataTable, 193, "Joy", "F")
        NoDataSource_Add_First_Name(oDataTable, 194, "Rick", "M")
        NoDataSource_Add_First_Name(oDataTable, 195, "Lester", "M")
        NoDataSource_Add_First_Name(oDataTable, 196, "Constance", "F")
        NoDataSource_Add_First_Name(oDataTable, 197, "Tamara", "F")
        NoDataSource_Add_First_Name(oDataTable, 198, "Allison", "F")
        NoDataSource_Add_First_Name(oDataTable, 199, "Sam", "M")
        NoDataSource_Add_First_Name(oDataTable, 200, "Colleen", "F")
    End Sub

    Private Sub NoDataSource_Add_First_Name(ByRef oDataTable As DataTable, ByVal ID As Integer, ByVal Name As String, ByVal sSex As String)
        Dim oDataRow As DataRow = Nothing
        oDataRow = oDataTable.NewRow()
        oDataRow("ID") = ID
        oDataRow("Name") = Name
        oDataRow("sSex") = sSex
        oDataTable.Rows.Add(oDataRow)
    End Sub

    Private Sub NoDataSource_Add_US_Cities(ByRef oDataTable As DataTable)
        NoDataSource_Add_US_City(oDataTable, 9270, "Merrydale", "LA")
        NoDataSource_Add_US_City(oDataTable, 21822, "Hale Center", "TX")
        NoDataSource_Add_US_City(oDataTable, 10652, "St. Helen", "MI")
        NoDataSource_Add_US_City(oDataTable, 15221, "Morris village", "NY")
        NoDataSource_Add_US_City(oDataTable, 13115, "Missoula", "MT")
        NoDataSource_Add_US_City(oDataTable, 6839, "Rosedale", "IN")
        NoDataSource_Add_US_City(oDataTable, 22607, "Sundown", "TX")
        NoDataSource_Add_US_City(oDataTable, 5964, "Orland Park village", "IL")
        NoDataSource_Add_US_City(oDataTable, 15543, "Syosset", "NY")
        NoDataSource_Add_US_City(oDataTable, 13081, "Joplin", "MT")
        NoDataSource_Add_US_City(oDataTable, 22220, "New Boston", "TX")
        NoDataSource_Add_US_City(oDataTable, 13569, "Oak village", "NE")
        NoDataSource_Add_US_City(oDataTable, 19009, "Courtdale borough", "PA")
        NoDataSource_Add_US_City(oDataTable, 15720, "Bethlehem", "NC")
        NoDataSource_Add_US_City(oDataTable, 19680, "Park Forest Village", "PA")
        NoDataSource_Add_US_City(oDataTable, 13819, "Winchester", "NV")
        NoDataSource_Add_US_City(oDataTable, 508, "Anaktuvuk Pass", "AK")
        NoDataSource_Add_US_City(oDataTable, 12567, "Monett", "MO")
        NoDataSource_Add_US_City(oDataTable, 25146, "Woods Landing-Jelm", "WY")
        NoDataSource_Add_US_City(oDataTable, 14295, "Somerset", "NJ")
        NoDataSource_Add_US_City(oDataTable, 22991, "Pleasant Grove", "UT")
        NoDataSource_Add_US_City(oDataTable, 2359, "Pleasant Hill", "CA")
        NoDataSource_Add_US_City(oDataTable, 6315, "Wenona", "IL")
        NoDataSource_Add_US_City(oDataTable, 20599, "Burke", "SD")
        NoDataSource_Add_US_City(oDataTable, 21676, "El Campo", "TX")
        NoDataSource_Add_US_City(oDataTable, 20310, "Hartsville", "SC")
        NoDataSource_Add_US_City(oDataTable, 10906, "Chickamaw Beach", "MN")
        NoDataSource_Add_US_City(oDataTable, 23591, "Central Park", "WA")
        NoDataSource_Add_US_City(oDataTable, 12347, "Hall village", "MO")
        NoDataSource_Add_US_City(oDataTable, 13685, "Superior", "NE")
        NoDataSource_Add_US_City(oDataTable, 15552, "Thornwood", "NY")
        NoDataSource_Add_US_City(oDataTable, 22017, "Laredo Ranchettes", "TX")
        NoDataSource_Add_US_City(oDataTable, 20345, "Lakewood", "SC")
        NoDataSource_Add_US_City(oDataTable, 4568, "Raoul", "GA")
        NoDataSource_Add_US_City(oDataTable, 23395, "North Springfield", "VA")
        NoDataSource_Add_US_City(oDataTable, 6374, "Yorkville", "IL")
        NoDataSource_Add_US_City(oDataTable, 21774, "Gholson", "TX")
        NoDataSource_Add_US_City(oDataTable, 17052, "Grand River village", "OH")
        NoDataSource_Add_US_City(oDataTable, 21946, "Kendleton", "TX")
        NoDataSource_Add_US_City(oDataTable, 3601, "Islamorada, Village of Islands village", "FL")
        NoDataSource_Add_US_City(oDataTable, 16464, "Golva", "ND")
        NoDataSource_Add_US_City(oDataTable, 19452, "McKeesport", "PA")
        NoDataSource_Add_US_City(oDataTable, 10111, "Waltham", "MA")
        NoDataSource_Add_US_City(oDataTable, 227, "Homewood", "AL")
        NoDataSource_Add_US_City(oDataTable, 16935, "Deer Park", "OH")
        NoDataSource_Add_US_City(oDataTable, 740, "Pilot Station", "AK")
        NoDataSource_Add_US_City(oDataTable, 22386, "Ralls", "TX")
        NoDataSource_Add_US_City(oDataTable, 16669, "Upham", "ND")
        NoDataSource_Add_US_City(oDataTable, 6989, "Alburnett", "IA")
        NoDataSource_Add_US_City(oDataTable, 1083, "Williams", "AZ")
        NoDataSource_Add_US_City(oDataTable, 16176, "Sanford", "NC")
        NoDataSource_Add_US_City(oDataTable, 7000, "Alvord", "IA")
        NoDataSource_Add_US_City(oDataTable, 1549, "Summit", "AR")
        NoDataSource_Add_US_City(oDataTable, 11075, "Golden Valley", "MN")
        NoDataSource_Add_US_City(oDataTable, 19922, "Springdale borough", "PA")
        NoDataSource_Add_US_City(oDataTable, 21041, "Greenfield", "TN")
        NoDataSource_Add_US_City(oDataTable, 10150, "Allen village", "MI")
        NoDataSource_Add_US_City(oDataTable, 19427, "Loganton borough", "PA")
        NoDataSource_Add_US_City(oDataTable, 23215, "Claremont", "VA")
        NoDataSource_Add_US_City(oDataTable, 10350, "Freeport village", "MI")
        NoDataSource_Add_US_City(oDataTable, 12197, "Dalton", "MO")
        NoDataSource_Add_US_City(oDataTable, 54, "Brewton", "AL")
        NoDataSource_Add_US_City(oDataTable, 4491, "Montezuma", "GA")
        NoDataSource_Add_US_City(oDataTable, 6178, "Sparland village", "IL")
        NoDataSource_Add_US_City(oDataTable, 11687, "Chunky", "MS")
        NoDataSource_Add_US_City(oDataTable, 15506, "Sodus Point village", "NY")
        NoDataSource_Add_US_City(oDataTable, 2715, "Basalt", "CO")
        NoDataSource_Add_US_City(oDataTable, 21026, "Garland", "TN")
        NoDataSource_Add_US_City(oDataTable, 12699, "Purdy", "MO")
        NoDataSource_Add_US_City(oDataTable, 19465, "Manheim borough", "PA")
        NoDataSource_Add_US_City(oDataTable, 8966, "Stanford", "KY")
        NoDataSource_Add_US_City(oDataTable, 24287, "Sylvester", "WV")
        NoDataSource_Add_US_City(oDataTable, 18566, "Hood River", "OR")
        NoDataSource_Add_US_City(oDataTable, 25019, "Fort Bridger", "WY")
        NoDataSource_Add_US_City(oDataTable, 17232, "Malvern village", "OH")
        NoDataSource_Add_US_City(oDataTable, 23788, "Marblemount", "WA")
        NoDataSource_Add_US_City(oDataTable, 4670, "Trion", "GA")
        NoDataSource_Add_US_City(oDataTable, 5919, "North village", "IL")
        NoDataSource_Add_US_City(oDataTable, 22535, "Shady Hollow", "TX")
        NoDataSource_Add_US_City(oDataTable, 21146, "Newbern", "TN")
        NoDataSource_Add_US_City(oDataTable, 3665, "Lake Sarasota", "FL")
        NoDataSource_Add_US_City(oDataTable, 16330, "Alexander", "ND")
        NoDataSource_Add_US_City(oDataTable, 7881, "Waverly", "IA")
        NoDataSource_Add_US_City(oDataTable, 19281, "Hokendauqua", "PA")
        NoDataSource_Add_US_City(oDataTable, 10102, "Teaticket", "MA")
        NoDataSource_Add_US_City(oDataTable, 10632, "Rochester", "MI")
        NoDataSource_Add_US_City(oDataTable, 22926, "Lindon", "UT")
        NoDataSource_Add_US_City(oDataTable, 6493, "Crown Point", "IN")
        NoDataSource_Add_US_City(oDataTable, 8082, "Durham", "KS")
        NoDataSource_Add_US_City(oDataTable, 24415, "Cascade village", "WI")
        NoDataSource_Add_US_City(oDataTable, 14634, "Alexandria Bay village", "NY")
        NoDataSource_Add_US_City(oDataTable, 5607, "Holiday Hills village", "IL")
        NoDataSource_Add_US_City(oDataTable, 23059, "Virgin", "UT")
        NoDataSource_Add_US_City(oDataTable, 4708, "White", "GA")
        NoDataSource_Add_US_City(oDataTable, 13506, "Lorton village", "NE")
        NoDataSource_Add_US_City(oDataTable, 8934, "Salt Lick", "KY")
        NoDataSource_Add_US_City(oDataTable, 14223, "Perth Amboy", "NJ")
        NoDataSource_Add_US_City(oDataTable, 20181, "Woonsocket", "RI")
        NoDataSource_Add_US_City(oDataTable, 18804, "Avonmore borough", "PA")
        NoDataSource_Add_US_City(oDataTable, 1080, "Wickenburg", "AZ")
        NoDataSource_Add_US_City(oDataTable, 17976, "Forest Park", "OK")
        NoDataSource_Add_US_City(oDataTable, 10591, "Peck village", "MI")
        NoDataSource_Add_US_City(oDataTable, 2921, "Monument", "CO")
        NoDataSource_Add_US_City(oDataTable, 23961, "Sunnyside", "WA")
        NoDataSource_Add_US_City(oDataTable, 25053, "La Grange", "WY")
        NoDataSource_Add_US_City(oDataTable, 19143, "Fairfield borough", "PA")
        NoDataSource_Add_US_City(oDataTable, 7506, "Manilla", "IA")
        NoDataSource_Add_US_City(oDataTable, 23780, "Malden", "WA")
        NoDataSource_Add_US_City(oDataTable, 16435, "Fessenden", "ND")
        NoDataSource_Add_US_City(oDataTable, 8675, "Drakesboro", "KY")
        NoDataSource_Add_US_City(oDataTable, 23124, "Orleans village", "VT")
        NoDataSource_Add_US_City(oDataTable, 15695, "Ayden", "NC")
        NoDataSource_Add_US_City(oDataTable, 13633, "Rockville village", "NE")
        NoDataSource_Add_US_City(oDataTable, 22198, "Muleshoe", "TX")
        NoDataSource_Add_US_City(oDataTable, 292, "Mentone", "AL")
        NoDataSource_Add_US_City(oDataTable, 20120, "Windsor borough", "PA")
        NoDataSource_Add_US_City(oDataTable, 21309, "Alvin", "TX")
        NoDataSource_Add_US_City(oDataTable, 5420, "Elkhart village", "IL")
        NoDataSource_Add_US_City(oDataTable, 4069, "Wausau", "FL")
        NoDataSource_Add_US_City(oDataTable, 22210, "Natalia", "TX")
        NoDataSource_Add_US_City(oDataTable, 21353, "Bailey's Prairie village", "TX")
        NoDataSource_Add_US_City(oDataTable, 24541, "Glendale", "WI")
        NoDataSource_Add_US_City(oDataTable, 14991, "Greenvale", "NY")
        NoDataSource_Add_US_City(oDataTable, 20540, "Willington", "SC")
        NoDataSource_Add_US_City(oDataTable, 20942, "Burns", "TN")
        NoDataSource_Add_US_City(oDataTable, 21412, "Blossom", "TX")
        NoDataSource_Add_US_City(oDataTable, 8506, "Turon", "KS")
        NoDataSource_Add_US_City(oDataTable, 22280, "Orange", "TX")
        NoDataSource_Add_US_City(oDataTable, 21402, "Bishop", "TX")
        NoDataSource_Add_US_City(oDataTable, 5737, "Litchfield", "IL")
        NoDataSource_Add_US_City(oDataTable, 17499, "Riverlea village", "OH")
        NoDataSource_Add_US_City(oDataTable, 6522, "Eaton", "IN")
        NoDataSource_Add_US_City(oDataTable, 3820, "Ormond Beach", "FL")
        NoDataSource_Add_US_City(oDataTable, 3365, "Chuluota", "FL")
        NoDataSource_Add_US_City(oDataTable, 23193, "Burkeville", "VA")
        NoDataSource_Add_US_City(oDataTable, 22338, "Pittsburg", "TX")
        NoDataSource_Add_US_City(oDataTable, 13158, "Saddle Butte", "MT")
        NoDataSource_Add_US_City(oDataTable, 9008, "Whitesville", "KY")
        NoDataSource_Add_US_City(oDataTable, 16915, "Coshocton", "OH")
        NoDataSource_Add_US_City(oDataTable, 18269, "River Bottom", "OK")
        NoDataSource_Add_US_City(oDataTable, 2600, "Twain Harte", "CA")
        NoDataSource_Add_US_City(oDataTable, 23629, "Deer Park", "WA")
        NoDataSource_Add_US_City(oDataTable, 4606, "Sandy Springs", "GA")
        NoDataSource_Add_US_City(oDataTable, 3051, "Bethlehem Village", "CT")
        NoDataSource_Add_US_City(oDataTable, 1941, "Florence-Graham", "CA")
        NoDataSource_Add_US_City(oDataTable, 12046, "Bigelow village", "MO")
        NoDataSource_Add_US_City(oDataTable, 16805, "Bradner village", "OH")
        NoDataSource_Add_US_City(oDataTable, 6707, "Michigan", "IN")
        NoDataSource_Add_US_City(oDataTable, 20790, "Parmelee", "SD")
        NoDataSource_Add_US_City(oDataTable, 21160, "Oak Ridge", "TN")
        NoDataSource_Add_US_City(oDataTable, 13813, "Tonopah", "NV")
        NoDataSource_Add_US_City(oDataTable, 9026, "Worthington", "KY")
        NoDataSource_Add_US_City(oDataTable, 8238, "Lake Quivira", "KS")
        NoDataSource_Add_US_City(oDataTable, 22573, "South Padre Island", "TX")
        NoDataSource_Add_US_City(oDataTable, 15667, "Yorkshire", "NY")
        NoDataSource_Add_US_City(oDataTable, 18015, "Guthrie", "OK")
        NoDataSource_Add_US_City(oDataTable, 3289, "Belle Glade Camp", "FL")
        NoDataSource_Add_US_City(oDataTable, 8799, "Ledbetter", "KY")
        NoDataSource_Add_US_City(oDataTable, 14463, "Fort Sumner village", "NM")
        NoDataSource_Add_US_City(oDataTable, 2310, "Orange Cove", "CA")
        NoDataSource_Add_US_City(oDataTable, 12538, "Matthews", "MO")
        NoDataSource_Add_US_City(oDataTable, 22034, "La Ward", "TX")
        NoDataSource_Add_US_City(oDataTable, 6873, "Shoals", "IN")
        NoDataSource_Add_US_City(oDataTable, 16131, "Ranlo", "NC")
        NoDataSource_Add_US_City(oDataTable, 2257, "Mountain Ranch", "CA")
        NoDataSource_Add_US_City(oDataTable, 5963, "Orland Hills village", "IL")
        NoDataSource_Add_US_City(oDataTable, 3841, "Palm River-Clair Mel", "FL")
        NoDataSource_Add_US_City(oDataTable, 5903, "New Salem village", "IL")
        NoDataSource_Add_US_City(oDataTable, 10563, "Norway", "MI")
        NoDataSource_Add_US_City(oDataTable, 2834, "Gleneagle", "CO")
        NoDataSource_Add_US_City(oDataTable, 12196, "Dadeville village", "MO")
        NoDataSource_Add_US_City(oDataTable, 11052, "Freeborn", "MN")
        NoDataSource_Add_US_City(oDataTable, 2406, "Ridgemark", "CA")
        NoDataSource_Add_US_City(oDataTable, 6767, "New", "IN")
        NoDataSource_Add_US_City(oDataTable, 21508, "Central Gardens", "TX")
        NoDataSource_Add_US_City(oDataTable, 15010, "Harris Hill", "NY")
        NoDataSource_Add_US_City(oDataTable, 19538, "Moosic borough", "PA")
        NoDataSource_Add_US_City(oDataTable, 21758, "Galena Park", "TX")
        NoDataSource_Add_US_City(oDataTable, 2459, "San Geronimo", "CA")
        NoDataSource_Add_US_City(oDataTable, 13231, "Arlington village", "NE")
        NoDataSource_Add_US_City(oDataTable, 10075, "Salem", "MA")
        NoDataSource_Add_US_City(oDataTable, 8488, "Summerfield", "KS")
        NoDataSource_Add_US_City(oDataTable, 7495, "Macedonia", "IA")
        NoDataSource_Add_US_City(oDataTable, 9616, "Clinton", "MD")
        NoDataSource_Add_US_City(oDataTable, 18709, "Sutherlin", "OR")
        NoDataSource_Add_US_City(oDataTable, 10771, "Zilwaukee", "MI")
        NoDataSource_Add_US_City(oDataTable, 23793, "Martha Lake", "WA")
        NoDataSource_Add_US_City(oDataTable, 16002, "Long View", "NC")
        NoDataSource_Add_US_City(oDataTable, 15493, "Shrub Oak", "NY")
        NoDataSource_Add_US_City(oDataTable, 8153, "Goodland", "KS")
        NoDataSource_Add_US_City(oDataTable, 8874, "Okolona", "KY")
        NoDataSource_Add_US_City(oDataTable, 8193, "Hoisington", "KS")
        NoDataSource_Add_US_City(oDataTable, 17149, "Kettlersville village", "OH")
        NoDataSource_Add_US_City(oDataTable, 13049, "Grass Range", "MT")
        NoDataSource_Add_US_City(oDataTable, 10391, "Harper Woods", "MI")
        NoDataSource_Add_US_City(oDataTable, 22615, "Sweeny", "TX")
        NoDataSource_Add_US_City(oDataTable, 6927, "Versailles", "IN")
        NoDataSource_Add_US_City(oDataTable, 22311, "Pearland", "TX")
        NoDataSource_Add_US_City(oDataTable, 19630, "North East borough", "PA")
        NoDataSource_Add_US_City(oDataTable, 940, "Kachina Village", "AZ")
    End Sub

    Private Sub NoDataSource_Add_US_City(ByRef oDataTable As DataTable, ByVal ID As Integer, ByVal Name As String, ByVal State As String)
        Dim oDataRow As DataRow = Nothing
        oDataRow = oDataTable.NewRow()
        oDataRow("ID") = ID
        oDataRow("Name") = Name
        oDataRow("State") = State
        oDataTable.Rows.Add(oDataRow)
    End Sub

    Private Sub NoDataSource_Add_Last_Names(ByRef oDataTable As DataTable)
        NoDataSource_Add_Last_Name(oDataTable, 1, "Smith")
        NoDataSource_Add_Last_Name(oDataTable, 2, "Johnson")
        NoDataSource_Add_Last_Name(oDataTable, 3, "Williams")
        NoDataSource_Add_Last_Name(oDataTable, 4, "Jones")
        NoDataSource_Add_Last_Name(oDataTable, 5, "Brown")
        NoDataSource_Add_Last_Name(oDataTable, 6, "Davis")
        NoDataSource_Add_Last_Name(oDataTable, 7, "Miller")
        NoDataSource_Add_Last_Name(oDataTable, 8, "Wilson")
        NoDataSource_Add_Last_Name(oDataTable, 9, "Moore")
        NoDataSource_Add_Last_Name(oDataTable, 10, "Taylor")
        NoDataSource_Add_Last_Name(oDataTable, 11, "Anderson")
        NoDataSource_Add_Last_Name(oDataTable, 12, "Thomas")
        NoDataSource_Add_Last_Name(oDataTable, 13, "Jackson")
        NoDataSource_Add_Last_Name(oDataTable, 14, "White")
        NoDataSource_Add_Last_Name(oDataTable, 15, "Harris")
        NoDataSource_Add_Last_Name(oDataTable, 16, "Martin")
        NoDataSource_Add_Last_Name(oDataTable, 17, "Thompson")
        NoDataSource_Add_Last_Name(oDataTable, 18, "Garcia")
        NoDataSource_Add_Last_Name(oDataTable, 19, "Martinez")
        NoDataSource_Add_Last_Name(oDataTable, 20, "Robinson")
        NoDataSource_Add_Last_Name(oDataTable, 21, "Clark")
        NoDataSource_Add_Last_Name(oDataTable, 22, "Rodriguez")
        NoDataSource_Add_Last_Name(oDataTable, 23, "Lewis")
        NoDataSource_Add_Last_Name(oDataTable, 24, "Lee")
        NoDataSource_Add_Last_Name(oDataTable, 25, "Walker")
        NoDataSource_Add_Last_Name(oDataTable, 26, "Hall")
        NoDataSource_Add_Last_Name(oDataTable, 27, "Allen")
        NoDataSource_Add_Last_Name(oDataTable, 28, "Young")
        NoDataSource_Add_Last_Name(oDataTable, 29, "Hernandez")
        NoDataSource_Add_Last_Name(oDataTable, 30, "King")
        NoDataSource_Add_Last_Name(oDataTable, 31, "Wright")
        NoDataSource_Add_Last_Name(oDataTable, 32, "Lopez")
        NoDataSource_Add_Last_Name(oDataTable, 33, "Hill")
        NoDataSource_Add_Last_Name(oDataTable, 34, "Scott")
        NoDataSource_Add_Last_Name(oDataTable, 35, "Green")
        NoDataSource_Add_Last_Name(oDataTable, 36, "Adams")
        NoDataSource_Add_Last_Name(oDataTable, 37, "Baker")
        NoDataSource_Add_Last_Name(oDataTable, 38, "Gonzalez")
        NoDataSource_Add_Last_Name(oDataTable, 39, "Nelson")
        NoDataSource_Add_Last_Name(oDataTable, 40, "Carter")
        NoDataSource_Add_Last_Name(oDataTable, 41, "Mitchell")
        NoDataSource_Add_Last_Name(oDataTable, 42, "Perez")
        NoDataSource_Add_Last_Name(oDataTable, 43, "Roberts")
        NoDataSource_Add_Last_Name(oDataTable, 44, "Turner")
        NoDataSource_Add_Last_Name(oDataTable, 45, "Phillips")
        NoDataSource_Add_Last_Name(oDataTable, 46, "Campbell")
        NoDataSource_Add_Last_Name(oDataTable, 47, "Parker")
        NoDataSource_Add_Last_Name(oDataTable, 48, "Evans")
        NoDataSource_Add_Last_Name(oDataTable, 49, "Edwards")
        NoDataSource_Add_Last_Name(oDataTable, 50, "Collins")
        NoDataSource_Add_Last_Name(oDataTable, 51, "Stewart")
        NoDataSource_Add_Last_Name(oDataTable, 52, "Sanchez")
        NoDataSource_Add_Last_Name(oDataTable, 53, "Morris")
        NoDataSource_Add_Last_Name(oDataTable, 54, "Rogers")
        NoDataSource_Add_Last_Name(oDataTable, 55, "Reed")
        NoDataSource_Add_Last_Name(oDataTable, 56, "Cook")
        NoDataSource_Add_Last_Name(oDataTable, 57, "Morgan")
        NoDataSource_Add_Last_Name(oDataTable, 58, "Bell")
        NoDataSource_Add_Last_Name(oDataTable, 59, "Murphy")
        NoDataSource_Add_Last_Name(oDataTable, 60, "Bailey")
        NoDataSource_Add_Last_Name(oDataTable, 61, "Rivera")
        NoDataSource_Add_Last_Name(oDataTable, 62, "Cooper")
        NoDataSource_Add_Last_Name(oDataTable, 63, "Richardson")
        NoDataSource_Add_Last_Name(oDataTable, 64, "Cox")
        NoDataSource_Add_Last_Name(oDataTable, 65, "Howard")
        NoDataSource_Add_Last_Name(oDataTable, 66, "Ward")
        NoDataSource_Add_Last_Name(oDataTable, 67, "Torres")
        NoDataSource_Add_Last_Name(oDataTable, 68, "Peterson")
        NoDataSource_Add_Last_Name(oDataTable, 69, "Gray")
        NoDataSource_Add_Last_Name(oDataTable, 70, "Ramirez")
        NoDataSource_Add_Last_Name(oDataTable, 71, "James")
        NoDataSource_Add_Last_Name(oDataTable, 72, "Watson")
        NoDataSource_Add_Last_Name(oDataTable, 73, "Brooks")
        NoDataSource_Add_Last_Name(oDataTable, 74, "Kelly")
        NoDataSource_Add_Last_Name(oDataTable, 75, "Sanders")
        NoDataSource_Add_Last_Name(oDataTable, 76, "Price")
        NoDataSource_Add_Last_Name(oDataTable, 77, "Bennett")
        NoDataSource_Add_Last_Name(oDataTable, 78, "Wood")
        NoDataSource_Add_Last_Name(oDataTable, 79, "Barnes")
        NoDataSource_Add_Last_Name(oDataTable, 80, "Ross")
        NoDataSource_Add_Last_Name(oDataTable, 81, "Henderson")
        NoDataSource_Add_Last_Name(oDataTable, 82, "Coleman")
        NoDataSource_Add_Last_Name(oDataTable, 83, "Jenkins")
        NoDataSource_Add_Last_Name(oDataTable, 84, "Perry")
        NoDataSource_Add_Last_Name(oDataTable, 85, "Powell")
        NoDataSource_Add_Last_Name(oDataTable, 86, "Long")
        NoDataSource_Add_Last_Name(oDataTable, 87, "Patterson")
        NoDataSource_Add_Last_Name(oDataTable, 88, "Hughes")
        NoDataSource_Add_Last_Name(oDataTable, 89, "Flores")
        NoDataSource_Add_Last_Name(oDataTable, 90, "Washington")
        NoDataSource_Add_Last_Name(oDataTable, 91, "Butler")
        NoDataSource_Add_Last_Name(oDataTable, 92, "Simmons")
        NoDataSource_Add_Last_Name(oDataTable, 93, "Foster")
        NoDataSource_Add_Last_Name(oDataTable, 94, "Gonzales")
        NoDataSource_Add_Last_Name(oDataTable, 95, "Bryant")
        NoDataSource_Add_Last_Name(oDataTable, 96, "Alexander")
        NoDataSource_Add_Last_Name(oDataTable, 97, "Russell")
        NoDataSource_Add_Last_Name(oDataTable, 98, "Griffin")
        NoDataSource_Add_Last_Name(oDataTable, 99, "Diaz")
        NoDataSource_Add_Last_Name(oDataTable, 100, "Hayes")
        NoDataSource_Add_Last_Name(oDataTable, 101, "Myers")
        NoDataSource_Add_Last_Name(oDataTable, 102, "Ford")
        NoDataSource_Add_Last_Name(oDataTable, 103, "Hamilton")
        NoDataSource_Add_Last_Name(oDataTable, 104, "Graham")
        NoDataSource_Add_Last_Name(oDataTable, 105, "Sullivan")
        NoDataSource_Add_Last_Name(oDataTable, 106, "Wallace")
        NoDataSource_Add_Last_Name(oDataTable, 107, "Woods")
        NoDataSource_Add_Last_Name(oDataTable, 108, "Cole")
        NoDataSource_Add_Last_Name(oDataTable, 109, "West")
        NoDataSource_Add_Last_Name(oDataTable, 110, "Jordan")
        NoDataSource_Add_Last_Name(oDataTable, 111, "Owens")
        NoDataSource_Add_Last_Name(oDataTable, 112, "Reynolds")
        NoDataSource_Add_Last_Name(oDataTable, 113, "Fisher")
        NoDataSource_Add_Last_Name(oDataTable, 114, "Ellis")
        NoDataSource_Add_Last_Name(oDataTable, 115, "Harrison")
        NoDataSource_Add_Last_Name(oDataTable, 116, "Gibson")
        NoDataSource_Add_Last_Name(oDataTable, 117, "Mcdonald")
        NoDataSource_Add_Last_Name(oDataTable, 118, "Cruz")
        NoDataSource_Add_Last_Name(oDataTable, 119, "Marshall")
        NoDataSource_Add_Last_Name(oDataTable, 120, "Ortiz")
        NoDataSource_Add_Last_Name(oDataTable, 121, "Gomez")
        NoDataSource_Add_Last_Name(oDataTable, 122, "Murray")
        NoDataSource_Add_Last_Name(oDataTable, 123, "Freeman")
        NoDataSource_Add_Last_Name(oDataTable, 124, "Wells")
        NoDataSource_Add_Last_Name(oDataTable, 125, "Webb")
        NoDataSource_Add_Last_Name(oDataTable, 126, "Simpson")
        NoDataSource_Add_Last_Name(oDataTable, 127, "Stevens")
        NoDataSource_Add_Last_Name(oDataTable, 128, "Tucker")
        NoDataSource_Add_Last_Name(oDataTable, 129, "Porter")
        NoDataSource_Add_Last_Name(oDataTable, 130, "Hunter")
        NoDataSource_Add_Last_Name(oDataTable, 131, "Hicks")
        NoDataSource_Add_Last_Name(oDataTable, 132, "Crawford")
        NoDataSource_Add_Last_Name(oDataTable, 133, "Henry")
        NoDataSource_Add_Last_Name(oDataTable, 134, "Boyd")
        NoDataSource_Add_Last_Name(oDataTable, 135, "Mason")
        NoDataSource_Add_Last_Name(oDataTable, 136, "Morales")
        NoDataSource_Add_Last_Name(oDataTable, 137, "Kennedy")
        NoDataSource_Add_Last_Name(oDataTable, 138, "Warren")
        NoDataSource_Add_Last_Name(oDataTable, 139, "Dixon")
        NoDataSource_Add_Last_Name(oDataTable, 140, "Ramos")
        NoDataSource_Add_Last_Name(oDataTable, 141, "Reyes")
        NoDataSource_Add_Last_Name(oDataTable, 142, "Burns")
        NoDataSource_Add_Last_Name(oDataTable, 143, "Gordon")
        NoDataSource_Add_Last_Name(oDataTable, 144, "Shaw")
        NoDataSource_Add_Last_Name(oDataTable, 145, "Holmes")
        NoDataSource_Add_Last_Name(oDataTable, 146, "Rice")
        NoDataSource_Add_Last_Name(oDataTable, 147, "Robertson")
        NoDataSource_Add_Last_Name(oDataTable, 148, "Hunt")
        NoDataSource_Add_Last_Name(oDataTable, 149, "Black")
        NoDataSource_Add_Last_Name(oDataTable, 150, "Daniels")
        NoDataSource_Add_Last_Name(oDataTable, 151, "Palmer")
        NoDataSource_Add_Last_Name(oDataTable, 152, "Mills")
        NoDataSource_Add_Last_Name(oDataTable, 153, "Nichols")
        NoDataSource_Add_Last_Name(oDataTable, 154, "Grant")
        NoDataSource_Add_Last_Name(oDataTable, 155, "Knight")
        NoDataSource_Add_Last_Name(oDataTable, 156, "Ferguson")
        NoDataSource_Add_Last_Name(oDataTable, 157, "Rose")
        NoDataSource_Add_Last_Name(oDataTable, 158, "Stone")
        NoDataSource_Add_Last_Name(oDataTable, 159, "Hawkins")
        NoDataSource_Add_Last_Name(oDataTable, 160, "Dunn")
        NoDataSource_Add_Last_Name(oDataTable, 161, "Perkins")
        NoDataSource_Add_Last_Name(oDataTable, 162, "Hudson")
        NoDataSource_Add_Last_Name(oDataTable, 163, "Spencer")
        NoDataSource_Add_Last_Name(oDataTable, 164, "Gardner")
        NoDataSource_Add_Last_Name(oDataTable, 165, "Stephens")
        NoDataSource_Add_Last_Name(oDataTable, 166, "Payne")
        NoDataSource_Add_Last_Name(oDataTable, 167, "Pierce")
        NoDataSource_Add_Last_Name(oDataTable, 168, "Berry")
        NoDataSource_Add_Last_Name(oDataTable, 169, "Matthews")
        NoDataSource_Add_Last_Name(oDataTable, 170, "Arnold")
        NoDataSource_Add_Last_Name(oDataTable, 171, "Wagner")
        NoDataSource_Add_Last_Name(oDataTable, 172, "Willis")
        NoDataSource_Add_Last_Name(oDataTable, 173, "Ray")
        NoDataSource_Add_Last_Name(oDataTable, 174, "Watkins")
        NoDataSource_Add_Last_Name(oDataTable, 175, "Olson")
        NoDataSource_Add_Last_Name(oDataTable, 176, "Carroll")
        NoDataSource_Add_Last_Name(oDataTable, 177, "Duncan")
        NoDataSource_Add_Last_Name(oDataTable, 178, "Snyder")
        NoDataSource_Add_Last_Name(oDataTable, 179, "Hart")
        NoDataSource_Add_Last_Name(oDataTable, 180, "Cunningham")
        NoDataSource_Add_Last_Name(oDataTable, 181, "Bradley")
        NoDataSource_Add_Last_Name(oDataTable, 182, "Lane")
        NoDataSource_Add_Last_Name(oDataTable, 183, "Andrews")
        NoDataSource_Add_Last_Name(oDataTable, 184, "Ruiz")
        NoDataSource_Add_Last_Name(oDataTable, 185, "Harper")
        NoDataSource_Add_Last_Name(oDataTable, 186, "Fox")
        NoDataSource_Add_Last_Name(oDataTable, 187, "Riley")
        NoDataSource_Add_Last_Name(oDataTable, 188, "Armstrong")
        NoDataSource_Add_Last_Name(oDataTable, 189, "Carpenter")
        NoDataSource_Add_Last_Name(oDataTable, 190, "Weaver")
        NoDataSource_Add_Last_Name(oDataTable, 191, "Greene")
        NoDataSource_Add_Last_Name(oDataTable, 192, "Lawrence")
        NoDataSource_Add_Last_Name(oDataTable, 193, "Elliott")
        NoDataSource_Add_Last_Name(oDataTable, 194, "Chavez")
        NoDataSource_Add_Last_Name(oDataTable, 195, "Sims")
        NoDataSource_Add_Last_Name(oDataTable, 196, "Austin")
        NoDataSource_Add_Last_Name(oDataTable, 197, "Peters")
        NoDataSource_Add_Last_Name(oDataTable, 198, "Kelley")
        NoDataSource_Add_Last_Name(oDataTable, 199, "Franklin")
        NoDataSource_Add_Last_Name(oDataTable, 200, "Lawson")
    End Sub

    Private Sub NoDataSource_Add_Last_Name(ByRef oDataTable As DataTable, ByVal ID As Integer, ByVal LastName As String)
        Dim oDataRow As DataRow = Nothing
        oDataRow = oDataTable.NewRow()
        oDataRow("ID") = ID
        oDataRow("LastName") = LastName
        oDataTable.Rows.Add(oDataRow)
    End Sub

    Private Sub NoDataSource_Add_US_Streets(ByRef oDataTable As DataTable)
        NoDataSource_Add_US_Street(oDataTable, 1, "Alley", "Aly")
        NoDataSource_Add_US_Street(oDataTable, 2, "Annex", "Anx")
        NoDataSource_Add_US_Street(oDataTable, 3, "Arcade", "Arc")
        NoDataSource_Add_US_Street(oDataTable, 4, "Avenue", "Ave")
        NoDataSource_Add_US_Street(oDataTable, 5, "Bayoo", "Byu")
        NoDataSource_Add_US_Street(oDataTable, 6, "Beach", "Bch")
        NoDataSource_Add_US_Street(oDataTable, 7, "Bend", "Bnd")
        NoDataSource_Add_US_Street(oDataTable, 8, "Bluff", "Blf")
        NoDataSource_Add_US_Street(oDataTable, 9, "Bluffs", "Blfs")
        NoDataSource_Add_US_Street(oDataTable, 10, "Bottom", "Btm")
        NoDataSource_Add_US_Street(oDataTable, 11, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 12, "Branch", "Br")
        NoDataSource_Add_US_Street(oDataTable, 13, "Bridge", "Brg")
        NoDataSource_Add_US_Street(oDataTable, 14, "Brook", "Brk")
        NoDataSource_Add_US_Street(oDataTable, 15, "Brooks", "Brks")
        NoDataSource_Add_US_Street(oDataTable, 16, "Burg", "Bg")
        NoDataSource_Add_US_Street(oDataTable, 17, "Burgs", "Bgs")
        NoDataSource_Add_US_Street(oDataTable, 18, "Bypass", "Byp")
        NoDataSource_Add_US_Street(oDataTable, 19, "Camp", "Cp")
        NoDataSource_Add_US_Street(oDataTable, 20, "Canyon", "Cyn")
        NoDataSource_Add_US_Street(oDataTable, 21, "Cape", "Cpe")
        NoDataSource_Add_US_Street(oDataTable, 22, "Causeway", "Cswy")
        NoDataSource_Add_US_Street(oDataTable, 23, "Center", "Ctr")
        NoDataSource_Add_US_Street(oDataTable, 24, "Centers", "Ctrs")
        NoDataSource_Add_US_Street(oDataTable, 25, "Circle", "Cir")
        NoDataSource_Add_US_Street(oDataTable, 26, "Circles", "Cirs")
        NoDataSource_Add_US_Street(oDataTable, 27, "Cliff", "Clf")
        NoDataSource_Add_US_Street(oDataTable, 28, "Cliffs", "Clfs")
        NoDataSource_Add_US_Street(oDataTable, 29, "Club", "Clb")
        NoDataSource_Add_US_Street(oDataTable, 30, "Common", "Cmn")
        NoDataSource_Add_US_Street(oDataTable, 31, "Corner", "Cor")
        NoDataSource_Add_US_Street(oDataTable, 32, "Corners", "Cors")
        NoDataSource_Add_US_Street(oDataTable, 33, "Course", "Crse")
        NoDataSource_Add_US_Street(oDataTable, 34, "Court", "Ct")
        NoDataSource_Add_US_Street(oDataTable, 35, "Courts", "Cts")
        NoDataSource_Add_US_Street(oDataTable, 36, "Cove", "Cv")
        NoDataSource_Add_US_Street(oDataTable, 37, "Coves", "Cvs")
        NoDataSource_Add_US_Street(oDataTable, 38, "Creek", "Crk")
        NoDataSource_Add_US_Street(oDataTable, 39, "Crescent", "Cres")
        NoDataSource_Add_US_Street(oDataTable, 40, "Crest", "Crst")
        NoDataSource_Add_US_Street(oDataTable, 41, "Crossing", "Xing")
        NoDataSource_Add_US_Street(oDataTable, 42, "Crossroad", "Xrd")
        NoDataSource_Add_US_Street(oDataTable, 43, "Curve", "Curv")
        NoDataSource_Add_US_Street(oDataTable, 44, "Dale", "Dl")
        NoDataSource_Add_US_Street(oDataTable, 45, "Dam", "Dm")
        NoDataSource_Add_US_Street(oDataTable, 46, "Divide", "Dv")
        NoDataSource_Add_US_Street(oDataTable, 47, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 48, "Drives", "Drs")
        NoDataSource_Add_US_Street(oDataTable, 49, "Estate", "Est")
        NoDataSource_Add_US_Street(oDataTable, 50, "Estates", "Ests")
        NoDataSource_Add_US_Street(oDataTable, 51, "Expressway", "Expy")
        NoDataSource_Add_US_Street(oDataTable, 52, "Extension", "Ext")
        NoDataSource_Add_US_Street(oDataTable, 53, "Extensions", "Exts")
        NoDataSource_Add_US_Street(oDataTable, 54, "Fall", "Fall")
        NoDataSource_Add_US_Street(oDataTable, 55, "Falls", "Fls")
        NoDataSource_Add_US_Street(oDataTable, 56, "Ferry", "Fry")
        NoDataSource_Add_US_Street(oDataTable, 57, "Field", "Fld")
        NoDataSource_Add_US_Street(oDataTable, 58, "Fields", "Flds")
        NoDataSource_Add_US_Street(oDataTable, 59, "Flat", "Flt")
        NoDataSource_Add_US_Street(oDataTable, 60, "Flats", "Flts")
        NoDataSource_Add_US_Street(oDataTable, 61, "Ford", "Frd")
        NoDataSource_Add_US_Street(oDataTable, 62, "Fords", "Frds")
        NoDataSource_Add_US_Street(oDataTable, 63, "Forest", "Frst")
        NoDataSource_Add_US_Street(oDataTable, 64, "Forge", "Frg")
        NoDataSource_Add_US_Street(oDataTable, 65, "Forges", "Frgs")
        NoDataSource_Add_US_Street(oDataTable, 66, "Fork", "Frk")
        NoDataSource_Add_US_Street(oDataTable, 67, "Forks", "Frks")
        NoDataSource_Add_US_Street(oDataTable, 68, "Fort", "Ft")
        NoDataSource_Add_US_Street(oDataTable, 69, "Freeway", "Fwy")
        NoDataSource_Add_US_Street(oDataTable, 70, "Garden", "Gdn")
        NoDataSource_Add_US_Street(oDataTable, 71, "Gardens", "Gdns")
        NoDataSource_Add_US_Street(oDataTable, 72, "Gateway", "Gtwy")
        NoDataSource_Add_US_Street(oDataTable, 73, "Glen", "Gln")
        NoDataSource_Add_US_Street(oDataTable, 74, "Glens", "Glns")
        NoDataSource_Add_US_Street(oDataTable, 75, "Green", "Grn")
        NoDataSource_Add_US_Street(oDataTable, 76, "Greens", "Grns")
        NoDataSource_Add_US_Street(oDataTable, 77, "Grove", "Grv")
        NoDataSource_Add_US_Street(oDataTable, 78, "Groves", "Grvs")
        NoDataSource_Add_US_Street(oDataTable, 79, "Harbor", "Hbr")
        NoDataSource_Add_US_Street(oDataTable, 80, "Harbors", "Hbrs")
        NoDataSource_Add_US_Street(oDataTable, 81, "Haven", "Hvn")
        NoDataSource_Add_US_Street(oDataTable, 82, "Heights", "Hts")
        NoDataSource_Add_US_Street(oDataTable, 83, "Highway", "Hwy")
        NoDataSource_Add_US_Street(oDataTable, 84, "Hill", "Hl")
        NoDataSource_Add_US_Street(oDataTable, 85, "Hills", "Hls")
        NoDataSource_Add_US_Street(oDataTable, 86, "Hollow", "Holw")
        NoDataSource_Add_US_Street(oDataTable, 87, "Inlet", "Inlt")
        NoDataSource_Add_US_Street(oDataTable, 88, "Island", "Is")
        NoDataSource_Add_US_Street(oDataTable, 89, "Islands", "Iss")
        NoDataSource_Add_US_Street(oDataTable, 90, "Isle", "Isle")
        NoDataSource_Add_US_Street(oDataTable, 91, "Junction", "Jct")
        NoDataSource_Add_US_Street(oDataTable, 92, "Junctions", "Jcts")
        NoDataSource_Add_US_Street(oDataTable, 93, "Key", "Ky")
        NoDataSource_Add_US_Street(oDataTable, 94, "Keys", "Kys")
        NoDataSource_Add_US_Street(oDataTable, 95, "Knoll", "Knl")
        NoDataSource_Add_US_Street(oDataTable, 96, "Knolls", "Knls")
        NoDataSource_Add_US_Street(oDataTable, 97, "Lake", "Lk")
        NoDataSource_Add_US_Street(oDataTable, 98, "Lakes", "Lks")
        NoDataSource_Add_US_Street(oDataTable, 99, "Land", "Land")
        NoDataSource_Add_US_Street(oDataTable, 100, "Landing", "Lndg")
        NoDataSource_Add_US_Street(oDataTable, 101, "Lane", "Ln")
        NoDataSource_Add_US_Street(oDataTable, 102, "Light", "Lgt")
        NoDataSource_Add_US_Street(oDataTable, 103, "Lights", "Lgts")
        NoDataSource_Add_US_Street(oDataTable, 104, "Loaf", "Lf")
        NoDataSource_Add_US_Street(oDataTable, 105, "Lock", "Lck")
        NoDataSource_Add_US_Street(oDataTable, 106, "Locks", "Lcks")
        NoDataSource_Add_US_Street(oDataTable, 107, "Lodge", "Ldg")
        NoDataSource_Add_US_Street(oDataTable, 108, "Loop", "Loop")
        NoDataSource_Add_US_Street(oDataTable, 109, "Mall", "Mall")
        NoDataSource_Add_US_Street(oDataTable, 110, "Manor", "Mnr")
        NoDataSource_Add_US_Street(oDataTable, 111, "Manors", "Mnrs")
        NoDataSource_Add_US_Street(oDataTable, 112, "Meadow", "Mdw")
        NoDataSource_Add_US_Street(oDataTable, 113, "Meadows", "Mdws")
        NoDataSource_Add_US_Street(oDataTable, 114, "Mews", "Mews")
        NoDataSource_Add_US_Street(oDataTable, 115, "Mill", "Ml")
        NoDataSource_Add_US_Street(oDataTable, 116, "Mills", "Mls")
        NoDataSource_Add_US_Street(oDataTable, 117, "Mission", "Msn")
        NoDataSource_Add_US_Street(oDataTable, 118, "Motorway", "Mtwy")
        NoDataSource_Add_US_Street(oDataTable, 119, "Mount", "Mt")
        NoDataSource_Add_US_Street(oDataTable, 120, "Mountain", "Mtn")
        NoDataSource_Add_US_Street(oDataTable, 121, "Mountains", "Mtns")
        NoDataSource_Add_US_Street(oDataTable, 122, "Neck", "Nck")
        NoDataSource_Add_US_Street(oDataTable, 123, "Orchard", "Orch")
        NoDataSource_Add_US_Street(oDataTable, 124, "Oval", "Oval")
        NoDataSource_Add_US_Street(oDataTable, 125, "Overpass", "Opas")
        NoDataSource_Add_US_Street(oDataTable, 126, "Park", "Park")
        NoDataSource_Add_US_Street(oDataTable, 127, "Parks", "Park")
        NoDataSource_Add_US_Street(oDataTable, 128, "Parkway", "Pkwy")
        NoDataSource_Add_US_Street(oDataTable, 129, "Parkways", "Pkwy")
        NoDataSource_Add_US_Street(oDataTable, 130, "Pass", "Pass")
        NoDataSource_Add_US_Street(oDataTable, 131, "Passage", "Psge")
        NoDataSource_Add_US_Street(oDataTable, 132, "Path", "Path")
        NoDataSource_Add_US_Street(oDataTable, 133, "Pike", "Pike")
        NoDataSource_Add_US_Street(oDataTable, 134, "Pine", "Pne")
        NoDataSource_Add_US_Street(oDataTable, 135, "Pines", "Pnes")
        NoDataSource_Add_US_Street(oDataTable, 136, "Place", "Pl")
        NoDataSource_Add_US_Street(oDataTable, 137, "Plain", "Pln")
        NoDataSource_Add_US_Street(oDataTable, 138, "Plains", "Plns")
        NoDataSource_Add_US_Street(oDataTable, 139, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 140, "Point", "Pt")
        NoDataSource_Add_US_Street(oDataTable, 141, "Points", "Pts")
        NoDataSource_Add_US_Street(oDataTable, 142, "Port", "Prt")
        NoDataSource_Add_US_Street(oDataTable, 143, "Ports", "Prts")
        NoDataSource_Add_US_Street(oDataTable, 144, "Prairie", "Pr")
        NoDataSource_Add_US_Street(oDataTable, 145, "Radial", "Radl")
        NoDataSource_Add_US_Street(oDataTable, 146, "Ramp", "Ramp")
        NoDataSource_Add_US_Street(oDataTable, 147, "Ranch", "Rnch")
        NoDataSource_Add_US_Street(oDataTable, 148, "Rapid", "Rpd")
        NoDataSource_Add_US_Street(oDataTable, 149, "Rapids", "Rpds")
        NoDataSource_Add_US_Street(oDataTable, 150, "Rest", "Rst")
        NoDataSource_Add_US_Street(oDataTable, 151, "Ridge", "Rdg")
        NoDataSource_Add_US_Street(oDataTable, 152, "Ridges", "Rdgs")
        NoDataSource_Add_US_Street(oDataTable, 153, "River", "Riv")
        NoDataSource_Add_US_Street(oDataTable, 154, "Road", "Rd")
        NoDataSource_Add_US_Street(oDataTable, 155, "Roads", "Rds")
        NoDataSource_Add_US_Street(oDataTable, 156, "Route", "Rte")
        NoDataSource_Add_US_Street(oDataTable, 157, "Row", "Row")
        NoDataSource_Add_US_Street(oDataTable, 158, "Rue", "Rue")
        NoDataSource_Add_US_Street(oDataTable, 159, "Run", "Run")
        NoDataSource_Add_US_Street(oDataTable, 160, "Shoal", "Shl")
        NoDataSource_Add_US_Street(oDataTable, 161, "Shoals", "Shls")
        NoDataSource_Add_US_Street(oDataTable, 162, "Shore", "Shr")
        NoDataSource_Add_US_Street(oDataTable, 163, "Shores", "Shrs")
        NoDataSource_Add_US_Street(oDataTable, 164, "Skyway", "Skwy")
        NoDataSource_Add_US_Street(oDataTable, 165, "Spring", "Spg")
        NoDataSource_Add_US_Street(oDataTable, 166, "Springs", "Spgs")
        NoDataSource_Add_US_Street(oDataTable, 167, "Spur", "Spur")
        NoDataSource_Add_US_Street(oDataTable, 168, "Spurs", "Spur")
        NoDataSource_Add_US_Street(oDataTable, 169, "Square", "Sq")
        NoDataSource_Add_US_Street(oDataTable, 170, "Squares", "Sqs")
        NoDataSource_Add_US_Street(oDataTable, 171, "Station", "Sta")
        NoDataSource_Add_US_Street(oDataTable, 172, "Stravenue", "Stra")
        NoDataSource_Add_US_Street(oDataTable, 173, "Stream", "Strm")
        NoDataSource_Add_US_Street(oDataTable, 174, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 175, "Streets", "Sts")
        NoDataSource_Add_US_Street(oDataTable, 176, "Summit", "Smt")
        NoDataSource_Add_US_Street(oDataTable, 177, "Terrace", "Ter")
        NoDataSource_Add_US_Street(oDataTable, 178, "Throughway", "Trwy")
        NoDataSource_Add_US_Street(oDataTable, 179, "Trace", "Trce")
        NoDataSource_Add_US_Street(oDataTable, 180, "Track", "Trak")
        NoDataSource_Add_US_Street(oDataTable, 181, "Trafficway", "Trfy")
        NoDataSource_Add_US_Street(oDataTable, 182, "Trail", "Trl")
        NoDataSource_Add_US_Street(oDataTable, 183, "Tunnel", "Tunl")
        NoDataSource_Add_US_Street(oDataTable, 184, "Turnpike", "Tpke")
        NoDataSource_Add_US_Street(oDataTable, 185, "Underpass", "Upas")
        NoDataSource_Add_US_Street(oDataTable, 186, "Union", "Un")
        NoDataSource_Add_US_Street(oDataTable, 187, "Unions", "Uns")
        NoDataSource_Add_US_Street(oDataTable, 188, "Valley", "Vly")
        NoDataSource_Add_US_Street(oDataTable, 189, "Valleys", "Vlys")
        NoDataSource_Add_US_Street(oDataTable, 190, "Viaduct", "Via")
        NoDataSource_Add_US_Street(oDataTable, 191, "View", "Vw")
        NoDataSource_Add_US_Street(oDataTable, 192, "Views", "Vws")
        NoDataSource_Add_US_Street(oDataTable, 193, "Village", "Vlg")
        NoDataSource_Add_US_Street(oDataTable, 194, "Villages", "Vlgs")
        NoDataSource_Add_US_Street(oDataTable, 195, "Ville", "Vl")
        NoDataSource_Add_US_Street(oDataTable, 196, "Vista", "Vis")
        NoDataSource_Add_US_Street(oDataTable, 197, "Walk", "Walk")
        NoDataSource_Add_US_Street(oDataTable, 198, "Walks", "Walk")
        NoDataSource_Add_US_Street(oDataTable, 199, "Wall", "Wall")
        NoDataSource_Add_US_Street(oDataTable, 200, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 201, "Ways", "Ways")
        NoDataSource_Add_US_Street(oDataTable, 202, "Well", "Wl")
        NoDataSource_Add_US_Street(oDataTable, 203, "Wells", "Wls")
        NoDataSource_Add_US_Street(oDataTable, 204, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 205, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 206, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 207, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 208, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 209, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 210, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 211, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 212, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 213, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 214, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 215, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 216, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 217, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 218, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 219, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 220, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 221, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 222, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 223, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 224, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 225, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 226, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 227, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 228, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 229, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 230, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 231, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 232, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 233, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 234, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 235, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 236, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 237, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 238, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 239, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 240, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 241, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 242, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 243, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 244, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 245, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 246, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 247, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 248, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 249, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 250, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 251, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 252, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 253, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 254, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 255, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 256, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 257, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 258, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 259, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 260, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 261, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 262, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 263, "Boulevard", "Blvd")
        NoDataSource_Add_US_Street(oDataTable, 264, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 265, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 266, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 267, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 268, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 269, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 270, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 271, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 272, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 273, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 274, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 275, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 276, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 277, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 278, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 279, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 280, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 281, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 282, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 283, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 284, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 285, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 286, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 287, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 288, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 289, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 290, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 291, "Plaza", "Plz")
        NoDataSource_Add_US_Street(oDataTable, 292, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 293, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 294, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 295, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 296, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 297, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 298, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 299, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 300, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 301, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 302, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 303, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 304, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 305, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 306, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 307, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 308, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 309, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 310, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 311, "Way", "Way")
        NoDataSource_Add_US_Street(oDataTable, 312, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 313, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 314, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 315, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 316, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 317, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 318, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 319, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 320, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 321, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 322, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 323, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 324, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 325, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 326, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 327, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 328, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 329, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 330, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 331, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 332, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 333, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 334, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 335, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 336, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 337, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 338, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 339, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 340, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 341, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 342, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 343, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 344, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 345, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 346, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 347, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 348, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 349, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 350, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 351, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 352, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 353, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 354, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 355, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 356, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 357, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 358, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 359, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 360, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 361, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 362, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 363, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 364, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 365, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 366, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 367, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 368, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 369, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 370, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 371, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 372, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 373, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 374, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 375, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 376, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 377, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 378, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 379, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 380, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 381, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 382, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 383, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 384, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 385, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 386, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 387, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 388, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 389, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 390, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 391, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 392, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 393, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 394, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 395, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 396, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 397, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 398, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 399, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 400, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 401, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 402, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 403, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 404, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 405, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 406, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 407, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 408, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 409, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 410, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 411, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 412, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 413, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 414, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 415, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 416, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 417, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 418, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 419, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 420, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 421, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 422, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 423, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 424, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 425, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 426, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 427, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 428, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 429, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 430, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 431, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 432, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 433, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 434, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 435, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 436, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 437, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 438, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 439, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 440, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 441, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 442, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 443, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 444, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 445, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 446, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 447, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 448, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 449, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 450, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 451, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 452, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 453, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 454, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 455, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 456, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 457, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 458, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 459, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 460, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 461, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 462, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 463, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 464, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 465, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 466, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 467, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 468, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 469, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 470, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 471, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 472, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 473, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 474, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 475, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 476, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 477, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 478, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 479, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 480, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 481, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 482, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 483, "Street", "St")
        NoDataSource_Add_US_Street(oDataTable, 484, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 485, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 486, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 487, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 488, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 489, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 490, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 491, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 492, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 493, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 494, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 495, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 496, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 497, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 498, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 499, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 500, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 501, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 502, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 503, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 504, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 505, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 506, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 507, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 508, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 509, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 510, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 511, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 512, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 513, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 514, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 515, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 516, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 517, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 518, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 519, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 520, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 521, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 522, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 523, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 524, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 525, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 526, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 527, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 528, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 529, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 530, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 531, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 532, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 533, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 534, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 535, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 536, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 537, "Drive", "Dr")
        NoDataSource_Add_US_Street(oDataTable, 538, "Drive", "Dr")
    End Sub

    Private Sub NoDataSource_Add_US_Street(ByRef oDataTable As DataTable, ByVal ID As Integer, ByVal Name As String, ByVal USPS As String)
        Dim oDataRow As DataRow = Nothing
        oDataRow = oDataTable.NewRow()
        oDataRow("ID") = ID
        oDataRow("Name") = Name
        oDataRow("USPS") = USPS
        oDataTable.Rows.Add(oDataRow)
    End Sub

    Public Function FromDate(ByVal dtDate As System.DateTime) As AGVBW.DateTime
        Dim dtReturn As AGVBW.DateTime = New AGVBW.DateTime(dtDate.Year, dtDate.Month, dtDate.Day, dtDate.Hour, dtDate.Minute, dtDate.Second)
        Return dtReturn
    End Function

End Module
